import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <img src="" alt="" />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="about">About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href="#">
          <img src="" alt="" />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
            assumenda illum qui. Reprehenderit facilis mollitia, suscipit optio,
            nesciunt quaerat repudiandae consectetur libero itaque obcaecati
            illum ducimus iusto numquam necessitatibus excepturi laboriosam,
            earum assumenda eaque. Eaque laboriosam officiis unde exercitationem
            est sunt, molestias impedit fugit hic nam? Quae eos aliquam vero!
          </p>
        </a>

        <a href="#">
          <img src="" alt="" />
          <h2>Events in Mosco</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
            assumenda illum qui. Reprehenderit facilis mollitia, suscipit optio,
            nesciunt quaerat repudiandae consectetur libero itaque obcaecati
            illum ducimus iusto numquam necessitatibus excepturi laboriosam,
            earum assumenda eaque. Eaque laboriosam officiis unde exercitationem
            est sunt, molestias impedit fugit hic nam? Quae eos aliquam vero!
          </p>
        </a>

        <a href="#">
          <img src="" alt="" />
          <h2>Events in New York</h2>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit
            assumenda illum qui. Reprehenderit facilis mollitia, suscipit optio,
            nesciunt quaerat repudiandae consectetur libero itaque obcaecati
            illum ducimus iusto numquam necessitatibus excepturi laboriosam,
            earum assumenda eaque. Eaque laboriosam officiis unde exercitationem
            est sunt, molestias impedit fugit hic nam? Quae eos aliquam vero!
          </p>
        </a>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
